version: '3'

services:
  web:
    build: .
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecnologias
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
